# Generated by Django 3.0.7 on 2020-08-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_preorder_preorderlineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
