# Generated by Django 3.0.7 on 2020-09-20 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='order_number',
            new_name='tracking_number',
        ),
    ]
