# Generated by Django 3.0.7 on 2020-09-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_auto_20200920_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
