# Generated by Django 3.0.7 on 2020-09-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='tracking_number',
            field=models.CharField(max_length=32),
        ),
    ]
