# Generated by Django 3.0.7 on 2020-09-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_auto_20200920_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_code',
        ),
    ]
