# Generated by Django 3.0.7 on 2020-09-21 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_remove_order_shipping_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='upgraded_order',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preorder', to='checkout.Order'),
        ),
    ]
