# Generated by Django 3.0.7 on 2020-09-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0016_preorder_upgraded_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pay_pal_order',
        ),
        migrations.AddField(
            model_name='order',
            name='pp_transaction_id',
            field=models.CharField(default='', max_length=254),
        ),
    ]
