# Generated by Django 3.0.7 on 2020-09-30 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0018_auto_20200921_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='expected_wait',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
