# Generated by Django 3.0.7 on 2020-09-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0019_auto_20200930_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='expected_wait',
            field=models.PositiveIntegerField(),
        ),
    ]
