# Generated by Django 3.0.7 on 2020-09-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0021_auto_20200930_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
