# Generated by Django 3.0.7 on 2020-07-03 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200701_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='height',
            new_name='h',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='length',
            new_name='l',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='width',
            new_name='w',
        ),
    ]
