# Generated by Django 3.0.7 on 2020-09-30 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='l',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
